### PR TITLE
Export common binaries

### PR DESCRIPTION
**Pull request by wholesomedev**
So...I started working on the `hollowverse/validate-filenames` package, and as expected I got annoyed when I tried to setup the repo from scratch. So I went back to my old routine of thinking of how to improve common config sharing. 

It occurred to me that maybe we don't need to have our common development and build time CLIs and their dependencies be `peerDependencies` but rather let `hollowverse/common` manage them and expose them.

That's what this PR does. If a downstream package depends on `hollowverse/common`, that downstream package then gets access to `common-prettier`, `common-eslint`, `common-tslint`, `common-tsc`, etc. That way, the downstream package doesn't need to install those CLIs or their dependencies. It just needs to install `hollowverse/common`.

...not sure if I've overlooked anything but I've tested things out and everything seems to be working as expected.

Do you foresee any problems with this approach? Is it reasonable?

~~(I'll send a PR to `hollowverse/hollowverse` right now to show what it looks like to be using this new pattern)~~ This is the corresponding PR for `hollowverse/hollowverse` https://github.com/hollowverse/hollowverse/pull/213

#### To-do:
* [ ] Fix `yarn check-js` (For some reason, `yarn check-js` is erroring out due to checking `node_modules`. @forabi do you know how to fix this?)

### CODE REVIEW

**Comment by forabi** [comment]
> Fix yarn check-js (For some reason, yarn check-js is erroring out due to checking node_modules. 

On which repo did you run `check-js`?

**Comment by forabi** [comment]
> Do you foresee any problems with this approach? Is it reasonable?

I'm not sure how we should handle dependency upgrades in this setup. What if we need TS 2.7? Should we upgrade the dependency in `common` or add TypeScript as an immediate dependency of the other repo? If it's the latter then we still need to add the dependencies to the other repos anyway.

The way `peerDependencies` work makes sense to me. When you install `react-redux`, it does not install `redux` as a dependency, because you may want a later or an older version of `redux`. `react-redux` does not _depend_ on `redux` directly, it expects that _your project_ depends on it. So it makes sense to have `redux` as a peer dependency for `react-redux`, and `yarn` warns you in case you don't have it installed. I think the same logic applies for `common`.

Still, I don't have a strong opinion on that matter. If that makes it easier to start a new repo and does not create any issues with upgrades, let's do it!

**Comment by forabi** [comment]
As a possible alternative solution, we could add a post install script for `common` that adds the required peer dependencies to the project if they are missing. In that scenario, we would just have to `yarn add hollowverse/common` and all the peer dependencies will be installed automatically. We could further improve that idea to also create the linter configuration files in case they are missing.

**Comment by wholesomedev** [comment]
@forabi As we discussed on Discord, I tried keeping the original names in `hollowverse/common` and then used it in `hollowverse/hollowverse`. All the required dependencies (tslint, prettier, eslint, tsc, etc) were installed in `hollowverse/hollowverse/node_modules/.bin` but they symlinked to their original locations, not `hollowverse/common`! 

Because I'm not sure why that's happening, I don't feel comfortable proceeding with this solution. It's also a non-standard practice so without sufficient knowledge of what's going on behind the scenes, we risk introducing issues.

...I'll consider this some more, but will probably eventually close this PR.

I'm not sure how the alternative solution you proposed would work. But I'm up for any solution that will make setting up a new repo easier!

**Comment by forabi** [comment]
> All the required dependencies (tslint, prettier, eslint, tsc, etc) were installed in hollowverse/hollowverse/node_modules/.bin but they symlinked to their original locations, not hollowverse/common!

Was that behavior consistent? I kind of expected this to be non-deterministic.

> I'm not sure how the alternative solution you proposed would work. But I'm up for any solution that would make setting up a new repo easier!
Packages can specify [a `postinstall` script](https://docs.npmjs.com/misc/scripts) in their `package.json` file which will be executed when the package is installed as a dependency. The script can basically do anything (which, by the way, exposes a serious security risk).

We could write a simple JS script that would check if `.eslintrc.json`, for example, exists, and if not, creates one that extends from `@hollowverse/common/.eslintrc`. For new projects, the file won't be found, so it's safe to create one. When `hollowverse/common` is upgraded, the file will exist so we do not overwrite it.

The script would also copy all peer dependencies from this repo's `package.json` to the other repo's `package.json` as `devDependencies` (only if not already installed) and run `yarn` to install and lock the packages.

**Comment by wholesomedev** [comment]
> Was that behavior consistent? I kind of expected this to be non-deterministic.

I only tried it once. So I'm not sure if it would be consistent or not in the future.

> We could write a simple JS script that would check if `.eslintrc.json`, for example, exists, and if not, creates one that extends from `@hollowverse/common/.eslintrc`. For new projects, the file won't be found, so it's safe to create one. When `hollowverse/common` is upgraded, the file will exist so we do not overwrite it.

I doubt the dynamic creation of config files can be a simple task. 

Automatic installation of `peerDependencies` as part of the `postinstall` script would also not work, I think. I've tried a similar approach with `commonpkg` and I ran into issues. `postinstall` scripts cannot reliably interfere with the `yarn install` or `npm install` process of the downstream package.

Exporting a binary from `hollowverse/common` that the developer can manually run to install the `hollowverse/common` `peerDependencies` might work. But that only solves one part of the problem so I'm not that enthusiastic about it.

**Comment by forabi** [comment]
> I doubt the dynamic creation of config files can be a simple task.

Can you elaborate on this? I don't see why. We could have a template of the extending file in this repo and just copy it to the root of the project.

> Automatic installation of peerDependencies as part of the postinstall script would also not work, I think. I've tried a similar approach with commonpkg and I ran into issues. postinstall scripts cannot reliably interfere with the yarn install or npm install process of the downstream package.

Is that because writing to `package.json` during installation causes some race condition? If not, what if we do not run yarn automatically and instead only copy the dependencies to `package.json` and then print a note that the user needs to run `yarn` again?

**Comment by forabi** [comment]
> I doubt the dynamic creation of config files can be a simple task.

In case it wasn't clear: I didn't mean we try to extend an already existing file with new fields. Either the file does not exist, so we create it, or it does exist, in which case we do nothing.

**Comment by wholesomedev** [comment]
@forabi What you're saying is starting to make more sense. But the more I think about what you're saying, the more my thoughts are leading me to the idea of simply creating a `hollowverse/template` repo which has our initial setup and we can clone that repo and build from there. We could use it with [`degit`](https://github.com/Rich-Harris/degit) to avoid git history issues.

**Comment by forabi** [comment]
@wholesomedev one difference between the suggested approach and `degit` would be that the former could add new dependencies and configuration files by upgrading `hollowverse/common`. `degit`, on the other hand, would copy a snapshot of the template repo at a specific point in time.

**Comment by wholesomedev** [comment]
@forabi The `degit` approach is dead simple though. I could get it setup in two hours. With what you're suggesting, I'm not really sure how to implement it with the "upgrade" functionality?

**Comment by forabi** [comment]
> With what you're suggesting, I'm not really sure how to implement it with the "upgrade" functionality?

I think `postinstall` is executed on upgrades as well, so our script could run again and add new configuration files, while skipping the already existing ones. We shouldn't need to write extra code to get this working.

I agree that `degit` is much simpler though.

**Comment by wholesomedev** [comment]
There is no further action that I can take on this at this moment. Will close for now...

**Pull request closed without merging**
